# -*- coding: utf-8 -*-
"""day2_task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UbAPRImgmrOnJRj31LmSq7pxHwc0qu30
"""

# Store career options in a list or in variables

career_options = ['medicine', 'journalism', 'technology',]

career_advices = ['Seek internship opportunities',
                  'Grow your skills and knowledge',
                  'Keep your skills up-to-date']

career_questions = ['What is your favourite area of study? \
Sciences, Languages, Technology: ', 'Do you prefer to work onsite or offsite?: ']

answer = []
for quest in career_questions: 
  answer.append(input(quest))



if answer[0] in ['languages','Languages', 'LANGUAGES']:
  print('Your career option is: Journalism')

elif answer[0] in ['sciences', 'Sciences', 'SCIENCES'] \
and answer[1] in['onsite', 'Onsite', 'ONSITE']:
  print('Your career option is: Medicine')

elif answer[0] in ['sciences', 'Sciences', 'SCIENCES'] \
and answer[1] in['offsite', 'Offsite', 'OFFSITE']:
  print('Your career option is: Farming')

elif answer[0] in ['technology', 'Technology', 'TECHNOLOGY']:
  print('Your career option is: Technology')

else:
  print('ERROR! Choose from the available options')



# conditional statements that determines the user selected choice