# -*- coding: utf-8 -*-
"""taskone_dayone.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QyZglqT8FEJ7Y0dCwuu45735sAt3KIa8
"""

from datetime import date
import calendar

mydate = date.today()
calendar.day_name[mydate.weekday()]

days = ['Mon','Tue','Wed','Thu','Fri','Sat','Sun']

fare = {'Mon':100,'Tue':100,'Wed':100,'Thu':100,'Fri':100,'Sat':60,'Sun':80}

print('Date:', mydate)

print('Day: ', days[mydate.weekday()])

if days == 'Mon''Tue''Wed''Thu''Fri':
  print('Fare: ', 100);

elif 'Sat':
    print('Fare: ', 60)

else:
      print('Fare: ', 80)